on:
  push:
    branches:
      - erdipage
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Deploy Job docker image to azure

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Login to docker
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PAT }}

      - name: Build and push image
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ghcr.io/${{ github.repository }}/erdipage:latest, ghcr.io/${{ github.repository }}/erdipage:${{ github.sha }}

  merge-updates:
    name: Merge dependabot PRs if conditions are met
    needs: [build]
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - name: Dependabot metadata
        id: dependabot-metadata
        uses: dependabot/fetch-metadata@v1
        with:
          github-token: '${{ secrets.GITHUB_TOKEN }}'

      - name: Disable auto-merge for Major Dependabot PRs
        if: ${{ steps.dependabot-metadata.outputs.update-type == 'version-update:semver-major' }}
        run: echo "won't automerge because it is a major version"

      - name: Enable auto-merge for Minor Dependabot PRs
        if: ${{ steps.dependabot-metadata.outputs.update-type == 'version-update:semver-minor' || steps.dependabot-metadata.outputs.update-type == 'version-update:semver-patch' }}
        run: gh pr merge --auto --rebase "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}