on:
  push:
    branches:
      - erdipage

permissions:
  pages: write
  id-token: write

jobs:
  build-static-artifact:
    runs-on: ubuntu-latest
    name: Build and Deploy Job docker image to github

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Cache dependencies
        id: cache_dependencies
        uses: actions/cache@v3
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('package-lock.json') }}

      - name: Install dependencies
        shell: bash
        if: steps.cache_dependencies.outputs.cache-hit != 'true'
        run: npm ci

      - name: Build application with static artifact
        shell: bash
        if: steps.cache_dependencies.outputs.cache-hit != 'true'
        run: npm run build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out

      - name: Publish to GitHub Pages 🚀
        id: deployment
        uses: actions/deploy-pages@v4